
[theme]
primaryColor = "#EA7A05"          # Orange TIRCIS
backgroundColor = "#F0F0F0"       # Gris très clair
secondaryBackgroundColor = "#F5F5F5"  # Gris très clair
textColor = "#262730"             # Gris foncé
font = "sans serif"               # ou "monospace", "serif"
